# Configuration for Alacritty, the GPU enhanced terminal emulator

# Environment variables
# env = { TERM = "xterm-256color-italic" }

[window]
dimensions = { columns = 100, lines = 85 }
padding = { x = 0, y = 0 }
dynamic_padding = false
decorations = "buttonless"
startup_mode = "Windowed"
opacity = 1.0

[scrolling]
history = 0
multiplier = 3

[font]
normal = { family = "DroidSansM Nerd Font Mono", style = "Regular" }
bold = { family = "DroidSansM Nerd Font Mono", style = "Regular" }
italic = { family = "DroidSansM Nerd Font Mono", style = "Regular" }
size = 14.0
offset = { x = 0, y = 0 }
glyph_offset = { x = 0, y = 0 }
use_thin_strokes = true

draw_bold_text_with_bright_colors = false
custom_cursor_colors = true

[colors]
primary = { background = "0xffffff", foreground = "0x4d4d4c" }
cursor = { text = "0xffffff", cursor = "0x4d4d4c" }
normal = { black = "0xffffff", red = "0xc82829", green = "0x718c00", yellow = "0xeab700", blue = "0x4271ae", magenta = "0x8959a8", cyan = "0x3e999f", white = "0x4d4d4c" }
bright = { black = "0x8e908c", red = "0xf5871f", green = "0xe0e0e0", yellow = "0xd6d6d6", blue = "0x969896", magenta = "0x282a2e", cyan = "0xa3685a", white = "0x1d1f21" }

[bell]
animation = "EaseOutExpo"
color = "0xffffff"
duration = 0

[key_bindings]
[[key_bindings]]
key = "V"
mods = "Command"
action = "Paste"

[[key_bindings]]
key = "C"
mods = "Command"
action = "Copy"

[[key_bindings]]
key = "Q"
mods = "Command"
action = "Quit"

[[key_bindings]]
key = "N"
mods = "Command"
action = "SpawnNewInstance"

[[key_bindings]]
key = "Return"
mods = "Command"
action = "ToggleFullscreen"

[[key_bindings]]
key = "Home"
chars = "\x1bOH"
mode = "AppCursor"

[[key_bindings]]
key = "Home"
chars = "\x1b[H"
mode = "~AppCursor"

# Add more key bindings here...

[mouse]
double_click = { threshold = 300 }
triple_click = { threshold = 300 }
hide_when_typing = true

[selection]
semantic_escape_chars = ",│`|:\"'' ()[]{}<>"
save_to_clipboard = false

[[mouse_bindings]]
mouse = "Middle"
action = "PasteSelection"

[cursor]
style = "Block"
unfocused_hollow = true

live_config_reload = true

[debug]
render_timer = false
persistent_logging = false
log_level = "OFF"
print_events = false
ref_test = false

[shell]
program = "/usr/local/bin/fish"
args = ["--command=tmux"]

