# Configuration for Alacritty, the GPU enhanced terminal emulator

# Environment variables
# env = { TERM = "xterm-256color-italic" }

[font]
normal = { family = "JetBrainsMono NFP", style = "Regular" }
bold = { family = "JetBrainsMono NFP", style = "Regular" }
italic = { family = "JetBrainsMono NFP", style = "Regular" }

[shell]
  program = "wsl"
