# Configuration for Alacritty, the GPU enhanced terminal emulator

# Environment variables
# env = { TERM = "xterm-256color-italic" }

[window]
dimensions = { columns = 100, lines = 85 }
padding = { x = 0, y = 0 }
dynamic_padding = false
decorations = "buttonless"
startup_mode = "Windowed"
opacity = 1.0

[scrolling]
history = 0
multiplier = 3

[font]
normal = { family = "DroidSansM Nerd Font Mono", style = "Regular" }
bold = { family = "DroidSansM Nerd Font Mono", style = "Regular" }
italic = { family = "DroidSansM Nerd Font Mono", style = "Regular" }
size = 14.0
offset = { x = 0, y = 0 }
glyph_offset = { x = 0, y = 0 }
use_thin_strokes = true

draw_bold_text_with_bright_colors = false
custom_cursor_colors = true

[colors]
primary = { background = "0xffffff", foreground = "0x4d4d4c" }
cursor = { text = "0xffffff", cursor = "0x4d4d4c" }
normal = { black = "0xffffff", red = "0xc82829", green = "0x718c00", yellow = "0xeab700", blue = "0x4271ae", magenta = "0x8959a8", cyan = "0x3e999f", white = "0x4d4d4c" }
bright = { black = "0x8e908c", red = "0xf5871f", green = "0xe0e0e0", yellow = "0xd6d6d6", blue = "0x969896", magenta = "0x282a2e", cyan = "0xa3685a", white = "0x1d1f21" }

[bell]
animation = "EaseOutExpo"
color = "0xffffff"
duration = 0


