#!/bin/sh

cd "$DOTFILES" || exit 1
for folder in $(echo "$STOW_FOLDERS" | sed "s/,/ /g")
do
    echo "stow $folder"
    stow -D "$folder"
    stow "$folder"
done

# Create cross-directory symlinks that stow can't handle
./link