#!/usr/bin/env zsh
# TODO yigithanbalci 2026-03-29: do we really need this 
# stowrc does it, simpler script might do the work
if [[ -z $STOW_FOLDERS ]]; then
    STOW_FOLDERS="bin,kitty,lazygit,nvim,tmux,zsh"
fi

if [[ -z $DOTFILES ]]; then
    DOTFILES=$HOME/.dotfiles
fi

STOW_FOLDERS=$STOW_FOLDERS DOTFILES=$DOTFILES $DOTFILES/install
#TODO: add chmod +x script for the bin 
