[metadata]
name = "fish-history"
description = "A channel to select from your fish history"
requirements = ["fish"]

[source]
command = "fish -c 'builtin history' | awk '!seen[$0]++'"
display = "{}"
output = "{}"
no_sort = true
frecency = false

[actions.execute]
description = "Execute the selected command"
command = "fish -c '{}'"
mode = "execute"
