#:schema https://github.com/joshmedeski/sesh/raw/main/sesh.schema.json
# open the file manager
[[session]]
name = "Downloads 📥"
path = "~/Downloads"
startup_command = "yazi"

# open a file
[[session]]
name = "tmux config"
path = "~/c/dotfiles/tmux"
startup_command = "nvim tmux.conf"

# run a script to startup a node project
[[session]]
path = "~/c/joshmedeski.com"
startup_script = "~/.config/sesh/scripts/node_dev"
